# Generated by Django 5.2.8 on 2025-11-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AlterModelOptions(
            name="habitrecord",
            options={
                "get_latest_by": "date",
                "verbose_name": "Отметка привычки",
                "verbose_name_plural": "Отметки привычек",
            },
        ),
    ]
