# Generated by Django 5.2.8 on 2025-11-09 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diary_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="user",
            field=models.ForeignKey(
                help_text="Владелец записи дневника",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите или добавьте теги для записи",
                to="diary.tag",
                verbose_name="Теги",
            ),
        ),
    ]
