# Generated by Django 5.2.8 on 2025-11-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary_app", "0003_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Текст аффирмации"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Показывать в ротации"
                    ),
                ),
            ],
        ),
    ]
